<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StudioLaValse.DependencyInjection.Microsoft" Version="1.0.0" />
    <PackageReference Include="StudioLaValse.Drawable" Version="3.0.0" />
    <PackageReference Include="StudioLaValse.Drawable.Interaction" Version="3.0.0" />
    <PackageReference Include="StudioLaValse.Key" Version="1.0.1" />
    <PackageReference Include="StudioLaValse.ScoreDocument" Version="3.0.0" />
  </ItemGroup>

</Project>
