<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  
  <ItemGroup>
    <None Remove="Resources\Fonts\bravura\Bravura.otf" />
    <None Remove="Resources\Fonts\bravura\BravuraText.otf" />
    <None Remove="Resources\Fonts\campania\Campania.otf" />
    <None Remove="Resources\Fonts\edwin\Edwin-BdIta.otf" />
    <None Remove="Resources\Fonts\edwin\Edwin-Bold.otf" />
    <None Remove="Resources\Fonts\edwin\Edwin-Italic.otf" />
    <None Remove="Resources\Fonts\edwin\Edwin-Roman.otf" />
    <None Remove="Resources\Fonts\finalebroadway\FinaleBroadway.otf" />
    <None Remove="Resources\Fonts\finalebroadway\FinaleBroadwayText.otf" />
    <None Remove="Resources\Fonts\finalemaestro\FinaleMaestro.otf" />
    <None Remove="Resources\Fonts\finalemaestro\FinaleMaestroText-Regular.otf" />
  </ItemGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Resources\Fonts\bravura\Bravura.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\bravura\BravuraText.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\campania\Campania.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\edwin\Edwin-BdIta.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\edwin\Edwin-Bold.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\edwin\Edwin-Italic.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\edwin\Edwin-Roman.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\finalebroadway\FinaleBroadway.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\finalebroadway\FinaleBroadwayText.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\finalemaestro\FinaleMaestro.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Include="Resources\Fonts\finalemaestro\FinaleMaestroText-Regular.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.10" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.10" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.1.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="8.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PDFsharp" Version="6.0.0" />
    <PackageReference Include="StudioLaValse.CommandManager" Version="2.0.0" />
    <PackageReference Include="StudioLaValse.Drawable.Avalonia" Version="2.1.1" />
    <PackageReference Include="StudioLaValse.Drawable.Skia" Version="2.1.1" />
    <PackageReference Include="YamlDotNet" Version="15.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\StudioLaValse.Drawable\StudioLaValse.Drawable.Avalonia\StudioLaValse.Drawable.Avalonia.csproj" />
    <ProjectReference Include="..\..\StudioLaValse.Drawable\StudioLaValse.Drawable.Interaction\StudioLaValse.Drawable.Interaction.csproj" />
    <ProjectReference Include="..\..\StudioLaValse.Drawable\StudioLaValse.Drawable\StudioLaValse.Drawable.csproj" />
    <ProjectReference Include="..\..\StudioLaValse.ScoreDocument\StudioLaValse.ScoreDocument.Drawable\StudioLaValse.ScoreDocument.Drawable.csproj" />
    <ProjectReference Include="..\..\StudioLaValse.ScoreDocument\StudioLaValse.ScoreDocument.Implementation\StudioLaValse.ScoreDocument.Implementation.csproj" />
    <ProjectReference Include="..\..\StudioLaValse.ScoreDocument\StudioLaValse.ScoreDocument.Models\StudioLaValse.ScoreDocument.Models.csproj" />
    <ProjectReference Include="..\..\StudioLaValse.ScoreDocument\StudioLaValse.ScoreDocument.MusicXml\StudioLaValse.ScoreDocument.MusicXml.csproj" />
    <ProjectReference Include="..\Sinfonia.API\Sinfonia.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\MainControl.axaml.cs">
      <DependentUpon>MainControl.axaml</DependentUpon>
    </Compile>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="External\" />
  </ItemGroup>
</Project>
